#!/usr/bin/python 

import PyTango as Tg
import sys 

for arg in sys.argv[1:]:
    try:
        Tg.DeviceProxy('dserver/HazemeyerIocaste_PS/'+arg).Kill()
    except Tg.DevFailed,exc:
        print exc

