#!/bin/sh

## Generic launcher script for Python DS.
## Please note that copies of SERVER.py residing in the current directory
## will be preferred over the version in $SICILIA/ds

# map input arguments to names variables
SERVER=`basename $0`
INST=$1
# setup enviroment
PYTHONPATH+=":$SICILIA/ds/python/$SERVER"

# workaround for RT #3273
cd $SICILIA/ds/python/$SERVER
CMD="/usr/bin/python ./$SERVER.py $INST"
SCREEN="screen -dmS $SERVER-$INST"
if [ "$INST" = "-?" ]
then
    $CMD
else
    $SCREEN $CMD
fi
